version: 1.0.{build}

branches:
  only:
  - master

environment:
  STACK_ROOT: C:\sr
  STACK_VERSION: 1.9.3
  PYTHON_ARCH: "64"
  PYTHON_VERSION: 3.6
  PYTHON: C:\\Python36-x64
  TEST_WHEELINSTALL_ENV: wheelinstall-py36
  
  # Workaround a gnarly bug https://github.com/haskell/cabal/issues/5386
  # See: https://www.fpcomplete.com/blog/2018/06/sed-a-debugging-story
  # TODO: check if it's fixed once we switch to lst-13 and GHC 8.6
  TMP: "c:\\tmp"

  matrix:
    - STACK_YAML: stack.yaml

install:
  - choco install -y haskell-stack --version %STACK_VERSION%
  - stack setup > nul
  - choco install purescript

cache:
  - C:\sr -> '%STACK_YAML%'
  - .stack-work -> '%STACK_YAML%'

build_script:
  - stack build
  - stack install --local-bin-path bin
  - 7z a "bin\windows.tar.gz" "%APPVEYOR_BUILD_FOLDER%\bin\spago.exe"

test_script:
  - set PATH=C:\projects\spago\bin;%PATH%
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - cd test\spago-test && python ..\spago-test.py && cd ..\..

artifacts:
  - path: bin\windows.tar.gz
    name: spago

deploy:
  - provider: GitHub
    auth_token:
      secure: fJUuBdSozxDLZP2sDiBXf4dEjdSJPBhZvwI/3FII+4RNxow0wGEX5ZzEyeK2wN7q
    artifact: spago
    on:
      APPVEYOR_REPO_TAG: true
